Django_Test_V/Roombooking/urls.py
from django.urls import path
from HomeApp.views import *
from . import views
from django.urls import include, re_path

app_name = 'room-booking'

urlpatterns = [
    re_path('booking/', views.BookingPage_view_create_view, name='booking'),
]

Django_Test_V/Shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'store'

urlpatterns = [
    path('store/', views.store, name="store"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),

    # URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    path('product/test/', views.test, name="test"),

]

Django_Test_V/UserProfile/urls.py
from django.urls import path
from HomeApp.views import *
from . import views
from django.urls import include, re_path


urlpatterns = [
    re_path('userprofile/', views.User_View, name='profile'),
]

Django_Test_V/rattsoffer/urls.py
from django.urls import path
from . import views
from django.urls import include, re_path

urlpatterns = [
    re_path('rattsoffer/', views.rattsoffer, name='rattsoffer'),
]

Django_Test_V/Roombooking/models.py
from django.db import models
from django.conf import settings
from sqlite3 import *
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save


# Create your models here.


class RoomCategory(models.Model):
    Room_Category = models.CharField(max_length=50)
    Rate = models.FloatField()
    Description = models.TextField(max_length=2000, null=False)

    def __str__(self):
        return self.Room_Category


class RoomTypefield(models.Model):
    name = models.CharField(max_length=100)
    Rate = models.IntegerField()

    def __str__(self):
        return self.name


class BedTypefield(models.Model):
    name = models.CharField(max_length=100)
    Rate = models.IntegerField()

    def __str__(self):
        return self.name


Adult_choice = (
    ("1", "one"),
    ("2", "two"),
    ("3", "three"),
    ("4", "four"),
    ("5", "five"),
)

Children_choice = (
    ("1", "one"),
    ("2", "two"),
    ("3", "three"),
    ("4", "four"),
    ("5", "five"),
)

Destination_Hotel_choice = (
    ("kathmandu", "kathmandu"),
    ("bhaktapur", "bhaktapur"),
    ("sanga", "sanga"),
    ("banepa", "banepa"),
    ("dhulikhel", "dhulikhel"),
    ("panauti", "panauti"),
)

# Room_choice = (
#     ("with bathroom", "with bathroom"),
#     ("without bathroom", "without bathroom"),
#     ("deluxe room", "deluxe room"),
#     ("super deluxe room", "super deluxe room"),
#     ("normal room", "normal room"),
# )

Choose_Hotel_choice = (
    ("Annapurna", "Annapurna"),
    ("Kumar Hotel", "Kumar Hotel"),
    ("Hotel A One", "Hotel A One"),
    ("Family Resort", "Family Resort"),
    ("Dhulikhel Valley Resort", "Dhulikhel Valley Resort"),
    ("Dakshinkali Home Stay-OYO", "Dakshinkali Home Stay-OYO"),
    ("Bhaktapur Valley View Resort", "Bhaktapur Valley View Resort"),
    ("Panauti Hotel", "Panauti Hotel"),
    ("KU Home Stay", "KU Home Stay"),
    ("Devithan Valley Resort", "Devithan Valley Resort"),
    ("Chandeswori Home Stay-OYO", "Chandeswori Home Stay-OYO"),
    ("Kavre-Bhaktapur Valley Resort", "Kavre-Bhaktapur Valley Resort"),
    ("Ra.Ts Valley Resort", "Ra.Ts Valley Resort"),
)


# Bed_choice = (
#     ("Queen Size Bed", "Queen Size Bed"),
#     ("Deluxe Bed", "Deluxe Bed"),
#     ("Normal Bed", "Normal Bed"),
#     ("Double Bed", "Double Bed"),
#     ("Single Bed", "Single Bed"),
# )


class RoomBooking(models.Model):
    Name = models.CharField(max_length=200)
    Email = models.CharField(max_length=100, null=True, blank=True)
    Phone = models.IntegerField()
    District = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    Street = models.CharField(max_length=100, null=True, blank=True)
    Emergency_Phone = models.IntegerField()
    Country = models.CharField(max_length=100, null=True, blank=True)
    Arrive_Date = models.DateField(max_length=100, null=True, blank=True)
    Depart_Date = models.DateField(max_length=100, null=True, blank=True)
    Adult = models.CharField(max_length=100, choices=Adult_choice, null=True, blank=True)
    Children = models.CharField(max_length=100, choices=Children_choice, null=True, blank=True)
    Destination_Hotel = models.CharField(choices=Destination_Hotel_choice, max_length=100, null=True, blank=True)
    Room_Type = models.ForeignKey(RoomTypefield, on_delete=models.CASCADE, null=True, blank=True)
    Choose_Hotel = models.CharField(max_length=100, choices=Choose_Hotel_choice)
    Bed_type = models.ForeignKey(BedTypefield, on_delete=models.CASCADE, null=True, blank=True)
    Rate = models.FloatField(max_length=50, null=True, blank=True)
    Description = models.TextField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.Name


# @receiver(post_save, sender=RoomBooking)
# def Price(sender, instance, created, *args, **Kwargs):
#     rate = instance.Rate
#     print(instance.Rate,":::::::::::Instance:::::::::::::;;;")
#     rate.save()

Django_Test_V/UserProfile/models.py
from django.db import models

class userprofile(models.Model):
    Productname = models.CharField(max_length=200)
    Price = models.FloatField(max_length=50)
    Image = models.ImageField()

Django_Test_V/flightbooking/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.


class FlightCat(models.Model):
    Category = models.CharField(max_length=50)
    Rate = models.FloatField()
    Description = models.TextField(max_length=2000, null=False)

    def __str__(self):
        return self.Category


class FlightType(models.Model):
    One_Way = models.CharField(max_length=50, null=False)
    Two_Way= models.CharField(max_length=50, null=False)


class Flight(models.Model):
    Name = models.CharField(max_length=200)
    Email = models.CharField(max_length=100)
    Phone = models.IntegerField()
    District = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    Street = models.CharField(max_length=100)
    Emergency_Phone = models.IntegerField()
    Country = models.CharField(max_length=100)
    Departure_Date = models.DateField(max_length=50)
    Landing_Date = models.DateField(max_length=50)
    Adult = models.CharField(max_length=50)
    Children = models.CharField(max_length=50)
    Departure_Airport = models.CharField(max_length=50)
    Ticket_Type = models.CharField(max_length=50)
    Landing_Airport = models.CharField(max_length=50)
    Description = models.TextField(max_length=2000, null=False)
    Category = models.ForeignKey(FlightCat, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.Name


class FlightBook(models.Model):
    User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Flight = models.ForeignKey(Flight, on_delete=models.CASCADE)
    Departure_Date = models.DateField()
    Landing_Date = models.DateField()

    def __str__(self):
        return f'{self.user} has booked From = {self.Arrive_Date("%d-%b-%Y")} To = {self.Depart_Date("%d-%b-%Y")}'

Django_Test_V/rattsoffer/models.py
from django.db import models

class rattsoffer(models.Model):
    title = models.CharField(max_length=200)
    sub_title = models.CharField(max_length=500)
    detials = models.TextField(max_length=5000)


class packagedetails(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=100)
    details = models.TextField(max_length=5000)
    photo = models.ImageField()

Django_Test_V/Roombooking/forms.py
from django import forms
from datetime import datetime
from .models import RoomCategory
from .models import RoomBooking, RoomCategory
from sqlite3 import *


class AvailabilityForm(forms.Form):
    Arrive_Date = forms.DateField(
        required=True, input_formats=["%Y-%m-%d", "%Y-%m-%d"], widget=forms.DateInput(attrs={'type': 'date-local'}))
    Depart_Date = forms.DateField(
        required=True, input_formats=["%Y-%m-%d", "%Y-%m-%d"], widget=forms.DateInput(attrs={'type': 'date-local'}))


class RoomForm(forms.ModelForm):
    class Meta:
        model = RoomBooking
        fields = "__all__"

Django_Test_V/Roombooking/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import *
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from django.shortcuts import render
from django.db.models import Q
from .forms import AvailabilityForm, RoomForm
from .models import *


# Create your views here.

# @login_required(login_url="/login/")
def BookingPage_view_create_view(request):
    if request.method == "POST":
        print(":::::::::::::::::POST::::::::::::::::::::::::::::::::::::::::::")
        form = RoomForm(request.POST)
        if form.is_valid():
            print("::::::::::::::::::::Form valid:::::::::::::::::::::::::::::::::::::::")
            Name = form.cleaned_data['Name']
            Email = form.cleaned_data['Email']
            Phone = form.cleaned_data['Phone']
            District = form.cleaned_data['Phone']
            city = form.cleaned_data['city']
            Street = form.cleaned_data['Street']
            Emergency_Phone = form.cleaned_data['Emergency_Phone']
            Country = form.cleaned_data['Country']
            Arrive_Date = form.cleaned_data['Arrive_Date']
            Depart_Date = form.cleaned_data['Depart_Date']
            Adult = form.cleaned_data['Adult']
            Children = form.cleaned_data['Children']
            Destination_Hotel = form.cleaned_data['Destination_Hotel']
            Room_Type = form.cleaned_data['Room_Type']
            print(Room_Type,":::::::::::::::::::::::::::::::::::")
            Choose_Hotel = form.cleaned_data['Choose_Hotel']
            Bed_type = form.cleaned_data['Bed_type']
            Rate = form.cleaned_data['Rate']
            Description = form.cleaned_data['Description']

            Roombooking = RoomBooking.objects.create(
                Name=Name,
                Email=Email,
                Phone=Phone,
                District=District,
                city=city,
                Street=Street,
                Emergency_Phone=Emergency_Phone,
                Country=Country,
                Arrive_Date=Arrive_Date,
                Depart_Date=Depart_Date,
                Adult=Adult,
                Children=Children,
                Destination_Hotel=Destination_Hotel,
                Room_Type=Room_Type,
                Choose_Hotel=Choose_Hotel,
                Bed_type=Bed_type,
                Rate=Rate,
                Description=Description
            )
            Roombooking.save()
            messages.success(request, ('Asset Account was created successfully.'))
            return redirect(reverse('room-booking:booking'))
        else:
            print("Error Occured::: ", form.errors)
            context = {
                'form': form,
                'Adult_choice': Adult_choice,
                'Children_choice': Children_choice,
                'Destination_Hotel_choice': Destination_Hotel_choice,
                'Room_Type': RoomTypefield.objects.all(),
                'Choose_Hotel_choice': Choose_Hotel_choice,
                'Bed_type': BedTypefield.objects.all(),
            }
            return render(request, 'roombooking.html', context, {'form': form})
    else:
        form = RoomForm()
        context = {
            'form': form,
            'Adult_choice': Adult_choice,
            'Children_choice': Children_choice,
            'Destination_Hotel_choice': Destination_Hotel_choice,
            'Room_Type': RoomTypefield.objects.all(),
            'Choose_Hotel_choice': Choose_Hotel_choice,
            'Bed_type': BedTypefield.objects.all(),
        }
        return render(request, 'roombooking.html', context)

Django_Test_V/UserProfile/views.py
from django.urls import *
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
# Create your views here.


@login_required(login_url="/login/")
def User_View(request):
    return render(request,"userprofile.html")

Django_Test_V/flightbooking/views.py
from django.shortcuts import render

# Create your views here.

Django_Test_V/rattsoffer/views.py
from django.shortcuts import HttpResponse
from datetime import datetime
from django.shortcuts import render, redirect


def rattsoffer(request):
    return render(request, "rattsoffers.html")

Django_Test_V/templates/navbar.html
{% load static %}

<!-- navbar-->
      <header class="header bg-white">
        <div class="container px-0 px-lg-3">
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'store:store' %}"><span class="font-weight-bold text-uppercase text-dark">Welcome to Ra.TTs Shop!</span></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <!-- Link--><a class="nav-link active" href="{% url 'store:store' %}">Ra.TTs</a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}">{{cat_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories' %}">All Categories</a>
                  </div>
                </li>
              </ul>
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Cart<small class="text-gray">({{cart_items.count}})</small></a></li>
                  <li class="nav-item"><a class="nav-link" href="#"> <i class="far fa-heart mr-1"></i><small class="text-gray"> (0)</small></a></li>
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="fas fa-paperclip-alt mr-1 text-gray"></i>Statement</a></li> {% endcomment %}

                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i>Statement</a></a>
                        <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                            <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}">Cart</a>
                            <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}">Orders</a>
                        </div>
                    </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>

Django_Test_V/templates/roombooking.html
{% extends "base.html" %}
{% load static %}
{% block footer %}
{% endblock footer%}
{% block content %} {% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Booking</title>
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://kit.fontawesome.com/6dc45ef80b.js" crossorigin="anonymous"></script>
    <!-- custom css file link  -->
    <link rel="stylesheet" href="{%static '/css/roombooking.css'%}">
</head>
<body>
    <!-- header section starts  -->
    <header class="header">
        <a href="#" class="logo"> <img src="/static/images/Ra.TTsLogo.png" alt=""> </a>
        <div class="icons">
            <div class="fa-solid fa-bell" id="bell_btn"></div>
            <div class="fas fa-user" id="User-Profile"></div>
            <div class="fas fa-bars" id="menu_btn"></div>
        </div>
        <nav class="navbar">
            <a href="statement.html">Statement</a>
            <a href="bookinglist.html">Booking Lists</a>
            <a href="changepassword.html">Change Password</a>
            <a href="reportproblem.html">Report a Problem</a>
            <a href="customersupport.html">Customer Support</a>
            <a href="loginpage/Login.html">Log Out</a>
        </nav>
        <div action="" class="User-Profile">
            <img src="images/pic-4" alt="">
            <h2>User Name</h2>
            <h2>9800000000</h2>
            <h2>email11@gmail.com</h2>
        </div>
    </header>
    <!-- header section ends -->
    <!-- booking form starts -->
    <section>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}
            <!--  General -->
            <div class="form-group">
                <h3>Room Booking</h3>
                <h2 class="heading">Booking & contact</h2>
                <div class="controls">
                    <input type="text" id="name" class="floatLabel" name="Name">
                    <label>Name</label>
                </div>
                <div class="controls">
                    <input type="text" id="email" class="floatLabel" name="Email">
                    <label>Email</label>
                </div>
                <div class="controls">
                    <input type="tel" id="phone" class="floatLabel" name="Phone">
                    <label>Phone</label>
                </div>
                <div class="grid">
                    <div class="col-2-3">
                        <div class="controls">
                            <input type="text" id="street" class="floatLabel" name="District">
                            <label>District</label>
                        </div>
                    </div>
                    <div class="col-1-3">
                        <div class="controls">
                            <input type="text" id="street-number" class="floatLabel" name="city">
                            <label>City</label>
                        </div>
                    </div>
                </div>
                <div class="grid">
                    <div class="col-2-3">
                        <div class="controls">
                            <input type="text" id="city" class="floatLabel" name="Street">
                            <label>Street/Tole</label>
                        </div>
                    </div>
                    <div class="col-1-3">
                        <div class="controls">
                            <input type="text" id="post-code" class="floatLabel" name="Emergency_Phone">
                            <label>Emergency Phone</label>
                        </div>
                    </div>
                </div>
                <div class="controls">
                    <input type="text" id="country" class="floatLabel" name="Country">
                    <label>Country</label>
                </div>
            </div>
            <!--  Details -->
            <div class="form-group">
                {% csrf_token %}
                <h2 class="heading">Details</h2>
                <div class="grid">
                    <div class="col-1-4 col-1-4-sm">
                        <div class="controls">
                            <input type="date" id="arrive" class="floatLabel" name="Arrive_Date"
                                value="date('YYYY-MM-DD')">
                            <label class="label-date"><i class="fa fa-calendar"></i>Arrive</label>
                        </div>
                    </div>
                    <div class="col-1-4 col-1-4-sm">
                        <div class="controls">
                            <input type="date" id="depart" class="floatLabel" name="Depart_Date"
                                value="date('YYYY-MM-DD')" />
                            <label class="label-date"><i class="fa fa-calendar"></i>Depart</label>
                        </div>
                    </div>
                </div>
                <div class="grid">
                    <div class="col-1-3 col-1-3-sm">
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" id="id_Adult" name="Adult">
                                {% for Adult_choice in Adult_choice %}
                                <option value="{{ Adult_choice.0 }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Adult_choice.0 }}</option>
                                {% endfor %}
                            </select>
                            <label><i class="fa fa-male"></i>Adults 18+</label>
                        </div>
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" name="Children">
                                {% for Children_choice in Children_choice %}
                                <option value="{{ Children_choice.0 }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Children_choice.0 }}</option>
                                {% endfor %}
                            </select>
                            <label><i class="fa fa-child"></i>Children</label>
                        </div>
                    </div>
                    <div class="col-1-3 col-1-3-sm">
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" name="Destination_Hotel">
                                {% for Destination_Hotel_choice in Destination_Hotel_choice %}
                                <option value="{{ Destination_Hotel_choice.0 }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Destination_Hotel_choice.0 }}
                                </option>
                                {% endfor %}
                            </select>
                            <label><i class="fa fa-location-arrow"></i>Destination Hotel</label>
                        </div>
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" name="Room_Type" id="Rooms_Type" onclick="calculate()">
                                {% for Room_Type in Room_Type %}
                                <option value="{{ Room_Type.Rate }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Room_Type.name }}</option>
                                {% endfor %}
                            </select>
                            <label>Room Type</label>
                        </div>
                    </div>
                    <div class="col-1-3 col-1-3-sm">
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" name="Choose_Hotel">
                                {% for Choose_Hotel_choice in Choose_Hotel_choice %}
                                <option value="{{ Choose_Hotel_choice.0 }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Choose_Hotel_choice.0 }}
                                </option>
                                {% endfor %}
                            </select>
                            <label><i class="fa fa-hotel"></i>Choose Hotel</label>
                        </div>
                    </div>
                    <div class="col-1-3 col-1-3-sm">
                        <div class="controls">
                            <i class="fa fa-sort"></i>
                            <select class="floatLabel" name="Bed_type" id="bedType" onclick="calculate()">
                                {% for Bed_type in Bed_type %}
                                <option value="{{ Bed_type.Rate }}" required>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ Bed_type.name }}</option>
                                {% endfor %}
                            </select>
                            <label><i class="fa fa-bed"></i>Bed Type</label>
                        </div>
                    </div>
                </div>
                <div class="grid">
                    <div class="Total_Amount" id="totalAmountDisplay" style="display:none;">
                        Total Amount: <input id="totalAmount" class="Total_Amount" name="Rate" disabled></input>
                    </div>
                    <br>
                    <p class="info-text">Give your remarks and remaining data on the field below.</p>
                    <div class="controls">
                        <textarea name="Description" class="floatLabel" id="comments"></textarea>
                        <label> Remarks </label>
                    </div>
                    <button type="submit" value="Submit" class="col-1-4">Proceed</button>
                </div>
            </div>
            <!-- /.form-group -->
        </form>
    </section>
    <script>
        let adultRate = document.getElementById("id_Adult");
    </script>
    <script>
        function calculate() {
            var bedType = document.getElementById("bedType");
            var roomType = document.getElementById("Rooms_Type");
            var totalAmount = document.getElementById("totalAmount");
            var totalAmountDisplay = document.getElementById("totalAmountDisplay");
            var bedValue = bedType.options[bedType.selectedIndex].value;
            var roomValue = roomType.options[roomType.selectedIndex].value;
            console.log({roomValue})
            console.log({bedValue})
            if (!isEmpty(bedValue) && !isEmpty(roomValue)) {
                var bedAmount = parseFloat(bedValue).toFixed(2);
                  console.log({bedAmount})
                var roomAmount = parseFloat(roomValue).toFixed(2);
                  console.log({roomAmount})
                var total = +bedAmount + +roomAmount;
                console.log({total})
                totalAmount.value = parseFloat(total.toString()).toFixed(2);
                totalAmountDisplay.style.display = "block";
            }
            else
            {
                totalAmountDisplay.style.display = "none";
            }
        }
        //utility function to check empty value
        function isEmpty(val) {
            return (val === undefined || val == null || val.length <= 0) ? true : false;
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
    <script src='//raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery-ui-autocomplete.js'></script>
    <script
        src='//raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery.select-to-autocomplete.js'></script>
    <script
        src='//raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery.select-to-autocomplete.min.js'></script>
    <script src="{%static '/js/roombooking.js'%}"></script>
    <script src="{%static '/js/booking.js'%}"></script>
</body>
{% endblock content %}